### PR TITLE
attempt to fix #72

### LINKED ISSUE #72: multipart form data does not strip protocol newline
The last newline is not stripped from the multipart data in 
```ctx.request.formParams.data[key].body```

```
# org ist the original file
du -b org
90145   org

# down is the same file downloaded through prologue's static file sender
du -b down
90146   down
```

### PR DESCRIPTION
**Pull request by enthus1ast**
Signed-off-by: David Krause <krause@biochem2.uni-frankfurt.de>

i'm usesing a vscode plugin that removes unnecessary whitespaces, i hope that does not bother you :)

### CODE REVIEW

**Comment by ringabout** [comment]
I think you can use http server to test form.
 https://github.com/planety/prologue/blob/2d2db70dad2c0b08a3c14c9c90a0ce43d0e321b5/tests/start_server.nim#L50

https://github.com/planety/prologue/blob/2d2db70dad2c0b08a3c14c9c90a0ce43d0e321b5/tests/test_core/test_application.nim#L196

like 
```nim
proc uploadTest(ctx: Context) {.async.} =
  if ctx.request.reqMethod == HttpGet:
    await ctx.staticFileResponse("tests/static/upload.html", "")
  elif ctx.request.reqMethod == HttpPost:
    let 
      file = ctx.getUploadFile("file")
    
    doAssert ctx.request.formParams.data["upload"].body.len == testfile.len
    doAssert ctx.request.formParams.data["upload"].body == testfile
    doAssert parseInt(ctx.request.formParams.data["howLongValid"].body) == 3600

    resp fmt"<html><h1>{file.filename}</h1><p>{file.body.strip()}</p></html>"
```

**Comment by enthus1ast** [comment]
i wanted to just test the parsing, withouth any other code involved

**Comment by ringabout** [comment]
But the current implementation of  form only supports `\c\L`, but for linux the newline in file is converted into `\n`. You need use binary text or something else to pass the parsing tests.

**Comment by enthus1ast** [comment]
i'll write a small tool that converts text into seq with correct newlines, to get rid of the base64 and make it human readable

**Comment by enthus1ast** [comment]
> But the current implementation of form only supports `\c\L`, but for linux the newline in file is converted into `\n`. You need use binary text or something else to pass the parsing tests.

afaik mime needs to use `\c\L`

**Comment by enthus1ast** [comment]
@xflywind please review

**Comment by ringabout** [comment]
Great works! Thanks!

**Pull request merged**
