### PR TITLE
make example applications look like a real project

### PR DESCRIPTION
**Pull request by xyb**

### CODE REVIEW

**Comment by ringabout** [comment]
Please don't do this. We have additional examples for this goal.  I have a test and CI to test whether these examples compile or not.

https://github.com/planety/prologue-examples

I need to rely on latest changes to test them locally. I don't want rely on global installation.

**Comment by ringabout** [comment]
Sorry, rejected!

**Comment by xyb** [comment]
> I need to rely on latest changes to test them locally. I don't want rely on global installation.

It is actually running in your local development directory. The `config.nims` make the magic happen. I confirmed this by `nim c --verbosity:3 app.nim`:
```
CC: ../../src/prologue/core/httpcore/httplogue.nim: clang -c  -w -ferror-limit=3 -pthread   -I/Users/xieyanbo/.choosenim/toolchains/nim-1.4.0/lib -I/Users/xieyanbo/Projects/prologue/examples/basic -o /Users/xieyanbo/.cache/nim/app_d/@m..@s..@ssrc@sprologue@score@shttpcore@shttplogue.nim.c.o /Users/xieyanbo/.cache/nim/app_d/@m..@s..@ssrc@sprologue@score@shttpcore@shttplogue.nim.c
```
I even injected some bad code into the local prologue source, as a result, the build processing of examples was broken. This PR will not spoil the feeling of local development. Just relax and have a cup of coffee.

**Comment by ringabout** [comment]
LGTM!

**Pull request merged**
